import { BaseSeeder } from '@adonisjs/lucid/seeders'
import User from '#models/user'

export default class UserSeeder extends BaseSeeder {
  public async run() {
    const users = [
      {
        nickname: 'razdvach',
        firstname: 'David',
        surname: 'Vach',
        email: 'david@example.com',
        profilePicture: '/avatars/1_razdvach.jpg',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'Franta',
        firstname: 'Kristof',
        surname: 'Kmet',
        email: 'kristof@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'lucia',
        firstname: 'Lucia',
        surname: 'Testerka',
        email: 'lucia@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'anna',
        firstname: 'Anna',
        surname: 'Designer',
        email: 'anna@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'martin',
        firstname: 'Martin',
        surname: 'Fice',
        email: 'martin@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'peter',
        firstname: 'Peter',
        surname: 'CEO',
        email: 'peter@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'jana',
        firstname: 'Jana',
        surname: 'HR',
        email: 'jana@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'tomas',
        firstname: 'Tomáš',
        surname: 'DevOps',
        email: 'tomas@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'zuzana',
        firstname: 'Zuzana',
        surname: 'PM',
        email: 'zuzana@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'filip',
        firstname: 'Filip',
        surname: 'Intern',
        email: 'filip@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },

      // ---- ďalší používatelia ----
      {
        nickname: 'vera',
        firstname: 'Viera',
        surname: 'Support',
        email: 'vera@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'igor',
        firstname: 'Igor',
        surname: 'Developer',
        email: 'igor@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'maria',
        firstname: 'Mária',
        surname: 'Marketing',
        email: 'maria@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'pavol',
        firstname: 'Pavol',
        surname: 'Sales',
        email: 'pavol@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'andrej',
        firstname: 'Andrej',
        surname: 'Analyst',
        email: 'andrej@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'lenka',
        firstname: 'Lenka',
        surname: 'Designer',
        email: 'lenka@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'roman',
        firstname: 'Roman',
        surname: 'QA',
        email: 'roman@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'katka',
        firstname: 'Katarína',
        surname: 'Copywriter',
        email: 'katka@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'juraj',
        firstname: 'Juraj',
        surname: 'Architect',
        email: 'juraj@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'barbora',
        firstname: 'Barbora',
        surname: 'UX',
        email: 'barbora@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'dusan',
        firstname: 'Dušan',
        surname: 'Support',
        email: 'dusan@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'sofia',
        firstname: 'Sofia',
        surname: 'HR',
        email: 'sofia@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'lukas',
        firstname: 'Lukáš',
        surname: 'Backend',
        email: 'lukas@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'monika',
        firstname: 'Monika',
        surname: 'Product',
        email: 'monika@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'tibor',
        firstname: 'Tibor',
        surname: 'Tester',
        email: 'tibor@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'silvia',
        firstname: 'Silvia',
        surname: 'Account',
        email: 'silvia@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'michal',
        firstname: 'Michal',
        surname: 'Frontend',
        email: 'michal@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'natasa',
        firstname: 'Nataša',
        surname: 'Scrum',
        email: 'natasa@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'stefan',
        firstname: 'Štefan',
        surname: 'Security',
        email: 'stefan@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'renata',
        firstname: 'Renáta',
        surname: 'Legal',
        email: 'renata@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'ondrej',
        firstname: 'Ondrej',
        surname: 'Data',
        email: 'ondrej@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: true,
        password: 'password123',
      },
      {
        nickname: 'eva',
        firstname: 'Eva',
        surname: 'Coordinator',
        email: 'eva@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
      {
        nickname: 'patrik',
        firstname: 'Patrik',
        surname: 'Ops',
        email: 'patrik@example.com',
        profilePicture: '',
        status: 'normal',
        connection: 'online',
        notifyOnMentionOnly: false,
        password: 'password123',
      },
    ]

    // namiesto createMany → upsert podľa emailu
    for (const user of users) {
      await User.updateOrCreate(
        { email: user.email }, // vyhľadávací kľúč
        user // dáta na update / create
      )
    }

    console.log('✅ UserSeeder finished')
  }
}
